export const OBLIQUE_STRATEGIES = [
  "Abandon normal instruments",
  "Accept advice",
  "Accidentally on purpose",
  "Allow an easement (an easement is the abandonment of a stricture)",
  "Are there sections? Consider transitions",
  "Ask people to work against their better judgment",
  "Ask your body",
  "Be dirty",
  "Breathe more deeply",
  "Bridges — build — burn",
  "Change instrument roles",
  "Change nothing and continue with immaculate consistency",
  "Children's voices, speaking, singing",
  "Consider different fading systems",
  "Consult other sources — promising, unpromising",
  "Convert a melodic element into a rhythmic element",
  "Courage!",
  "Cut a vital connection",
  "Decorate, decorate",
  "Define an area as 'safe' and use it as an anchor",
  "Destroy nothing; Destroy the most important thing",
  "Discard an axiom",
  "Disconnect from desire",
  "Discover the recipes you are using and abandon them",
  "Distorting time",
  "Do nothing for as long as possible",
  "Do the words need changing?",
  "Don't avoid what is easy",
  "Don't break the silence",
  "Don't stress one thing more than another",
  "Do something boring",
  "Do the washing up",
  "Emphasize differences",
  "Emphasize repetitions",
  "Emphasize the flaws",
  "Faced with a choice, do both",
  "Fill every beat",
  "Find a safe part and use it as an anchor",
  "Get your neck massaged",
  "Ghost echoes",
  "Give the game away",
  "Give way to your worst impulse",
  "Go slowly all the way round the outside",
  "Honor thy error as a hidden intention",
  "How would you have done it?",
  "Humanize something free of error",
  "Idiot glee",
  "Imagine the piece as a set of disconnected events",
  "In total darkness, or in a very large room, very quietly",
  "Intentions — nobility of, to invade",
  "Into the impossible",
  "Is it finished?",
  "Is the style right?",
  "It is quite possible (after all)",
  "Just carry on",
  "Left channel, right channel, centre channel",
  "Listen in total darkness, or in a very large room, very quietly",
  "Look at a very small object; look at its centre",
  "Look at the order in which you do things",
  "Lost in useless territory",
  "Lowest common denominator check — single element, discard others; try it with the others",
  "Make a blank valuable by putting it in an exquisite frame",
  "Make an exhaustive list of everything you might do and do the last thing on the list",
  "Make a sudden, destructive, unpredictable action; incorporate",
  "Mechanize something idiosyncratic",
  "Mute and continue",
  "Not building a wall; making a brick",
  "Once the search has begun, something will be found",
  "Only one element of each kind",
  "Only one element of each kind",
  "Openly resist change",
  "Overtly resist change",
  "Pay attention to distractions",
  "Question the heroic approach",
  "Reconsider your relationships",
  "Remove ambiguities and convert to specifics",
  "Remove everything",
  "Remove specifics and convert to ambiguities",
  "Repetition is a form of change",
  "Revaluation (a warm feeling)",
  "Reverse",
  "Short circuit (example: a man eating peas with the idea that they will improve his virility shovels them straight into his lap)",
  "Shut the door and listen from outside",
  "Simply a matter of work",
  "Slow preparation, fast execution",
  "State the problem in words as clearly as possible",
  "Take a break",
  "Take away the elements in order of apparent non-importance",
  "Tape your mouth shut",
  "The inconsistency principle",
  "The most important thing is the thing most easily forgotten",
  "Think of the radio",
  "Tidy up",
  "Trust in the you of now",
  "Turn it upside down",
  "Twist the spine",
  "Use an old idea",
  "Use an unacceptable color",
  "Use fewer notes",
  "Use filters",
  "Use 'unqualified' people",
  "Water",
  "What are you really thinking about just now? Incorporate",
  "What is the reality of the situation?",
  "What mistakes did you make last time?",
  "What would your closest friend do?",
  "What wouldn't you do?",
  "Work at a different speed",
  "You are an engineer",
  "You can only make one dot at a time",
  "Your mistake was a hidden intention",
];

export const PROPHECY_TEMPLATES = [
  "When the {adjective} {noun} meets the {adjective2} {noun2}, so shall {outcome} be revealed.",
  "Seek not the {noun}, for it hides within the {noun2}. The {adjective} path leads to {outcome}.",
  "Three {noun}s must align before {outcome} can manifest. Look first to the {adjective} {noun2}.",
  "The {adjective} {noun} whispers of {outcome}. Heed the {noun2} that blooms in {adjective2} soil.",
  "As the {noun} turns {adjective}, so too shall {outcome} unfold. The {noun2} holds the key.",
  "Beyond the {adjective} {noun} lies {outcome}. The {noun2} is both map and mirror.",
  "Where {adjective} {noun} dares not tread, {outcome} takes root. Trust the {adjective2} {noun2}.",
];

export const PROPHECY_WORDS = {
  adjectives: ["crimson", "hollow", "wandering", "ancient", "forgotten", "luminous", "fractured", "silent", "burning", "dreaming", "inverted", "paradoxical", "tidal", "crystalline", "scattered"],
  nouns: ["compass", "mirror", "threshold", "echo", "tide", "anchor", "lantern", "bridge", "shadow", "thread", "keystone", "vessel", "current", "root", "storm"],
  outcomes: [
    "the answer you already know",
    "clarity born from confusion",
    "the path forward through surrender",
    "the solution disguised as an obstacle",
    "the question more valuable than its answer",
    "momentum hidden in stillness",
    "the connection you've been overlooking",
    "strength found in the abandoned approach",
    "the right question finally asked",
    "the simplicity beneath the complexity",
  ],
};

export const CREATIVE_CONSTRAINTS = [
  "Solve this as if you only have 5 minutes and no tools",
  "Approach this as if you're explaining it to a 10-year-old who will teach it back to adults",
  "What would the solution look like if it had to be completely reversible?",
  "Solve this using only what already exists — no new creations",
  "Approach this as if the current 'problem' is actually the solution to a different problem",
  "What if you had to solve this in exactly 3 steps, no more, no less?",
  "Solve this as if every resource is infinitely available except time",
  "What would the solution look like if it had to be beautiful?",
  "Approach this as if the simplest solution is definitely wrong",
  "What if the constraint IS the feature?",
  "Solve this as if you could only communicate using questions",
  "What would a chef do with this problem?",
  "Approach this as a jazz musician: improvise first, then transcribe",
  "What would the solution look like 10 years from now, worked backwards?",
  "Solve this as if you're not allowed to address it directly",
  "What if you had to make the problem worse first before making it better?",
  "Approach this as if you're writing the last chapter first",
  "What would a cartographer do with this problem?",
  "Solve this as if the goal is to create the most interesting failure",
  "What if the answer requires unlearning one thing you know?",
  "Approach this as a sculptor: what do you remove to reveal the solution?",
  "What would this look like if it had to work silently, in the background?",
  "Solve this as if you'll need to hand it to a stranger to finish",
  "What if solving this requires doing something embarrassing?",
  "Approach this as if ambiguity is the product, not the problem",
];

export const DEV_FORTUNES = [
  "A bug you haven't written yet will be your finest work.",
  "The function you're about to delete is the one the universe needs.",
  "Your next commit message will finally be accurate.",
  "An unexpected dependency will become your greatest ally.",
  "The merge conflict you fear will resolve itself if you wait one more hour.",
  "A rubber duck is about to speak. Listen carefully.",
  "The comment you almost deleted contains the answer.",
  "Your best refactor will come from doing nothing today.",
  "The test you skipped will reveal a hidden truth tomorrow.",
  "An ancient Stack Overflow post from 2009 holds your salvation.",
  "The person who will fix your hardest bug hasn't read your code yet.",
  "Your naming convention will make perfect sense to exactly one future developer.",
  "The abstraction you're about to create already exists three files away.",
  "A semicolon will save you hours this week.",
  "The README you write tonight will be the kindest thing you do for yourself.",
  "Your environment variables are trying to tell you something.",
  "The race condition will not manifest in production. This time.",
  "Simplicity approaches. Do not flee from it.",
  "The log you added for debugging will catch a real bug in production.",
  "Your cache will be invalidated at the exact right moment.",
  "The type error is a gift in disguise.",
  "Sleep is the debugger you haven't tried yet.",
  "The PR that seemed impossible will be approved with no comments.",
  "A new pair of eyes will see what you cannot. Ask for them.",
  "The complexity you feel now will become elegance you understand later.",
];

export const PERSPECTIVE_INVERSIONS = [
  { pattern: "bug", inversion: "What if this 'bug' is surfacing a constraint that was always there but invisible? The code is being honest." },
  { pattern: "slow", inversion: "What if the slowness is telling you the operation is more significant than you thought? Honor the weight of it." },
  { pattern: "confusing", inversion: "What if the confusion is accurate — the domain itself is confused, and clarity would be a lie?" },
  { pattern: "too complex", inversion: "What if the complexity is the right answer, and simplifying it would destroy something essential?" },
  { pattern: "broken", inversion: "What if it's not broken but transitioning? Every caterpillar looks broken mid-metamorphosis." },
  { pattern: "error", inversion: "What if the error is more informative than success would have been? Errors are the system speaking." },
  { pattern: "failing", inversion: "What if failing at this is succeeding at finding out it's the wrong thing to do?" },
  { pattern: "missing", inversion: "What if the absence is the feature? Some systems are defined by what they exclude." },
  { pattern: "redundant", inversion: "What if the redundancy is resilience? Repetition is how the universe survives." },
  { pattern: "legacy", inversion: "What if the old code isn't legacy but load-bearing? It has survived longer than the new code has been tested." },
];

export const COSMIC_BRIDGES = [
  "Both are systems that collapse when observed too closely.",
  "Both reach equilibrium through apparent chaos.",
  "Both are defined more by what they exclude than what they contain.",
  "Both require a leap of faith at a critical transition.",
  "Both improve by accepting rather than fighting their nature.",
  "Both have a 'good enough' threshold beyond which optimization causes harm.",
  "Both exist in a superposition until forced to commit.",
  "Both are emergent — the whole cannot be predicted from the parts.",
  "Both have a hidden dependency that, if removed, would collapse everything.",
  "Both are solved not by adding but by removing the right thing.",
  "Both require you to hold contradiction without resolving it.",
  "Both look completely different when you change the level of abstraction.",
  "Both have a rhythm — violate it and they resist, honor it and they flow.",
  "Both are conversations between structure and chaos, not victories of one over the other.",
  "Both contain within them the seed of their own undoing — and that is their strength.",
];
